// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOrSxXb5pn0WjnyBLQQliREOtVuDVs6_Q',
    appId: '1:578747395600:web:79f0b7ff99b44540136495',
    messagingSenderId: '578747395600',
    projectId: 'coro-app-jovenes-lldm',
    authDomain: 'coro-app-jovenes-lldm.firebaseapp.com',
    storageBucket: 'coro-app-jovenes-lldm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhsXvHEzScb6epf-tBOTRA5wtQ97iz0tM',
    appId: '1:578747395600:android:f8ed6aab065d6196136495',
    messagingSenderId: '578747395600',
    projectId: 'coro-app-jovenes-lldm',
    storageBucket: 'coro-app-jovenes-lldm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoIWWs_cUj_ghRVspihHO6a-qXnxb1SzI',
    appId: '1:578747395600:ios:181edaf067f22088136495',
    messagingSenderId: '578747395600',
    projectId: 'coro-app-jovenes-lldm',
    storageBucket: 'coro-app-jovenes-lldm.firebasestorage.app',
    iosBundleId: 'com.example.corohpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoIWWs_cUj_ghRVspihHO6a-qXnxb1SzI',
    appId: '1:578747395600:ios:181edaf067f22088136495',
    messagingSenderId: '578747395600',
    projectId: 'coro-app-jovenes-lldm',
    storageBucket: 'coro-app-jovenes-lldm.firebasestorage.app',
    iosBundleId: 'com.example.corohpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOrSxXb5pn0WjnyBLQQliREOtVuDVs6_Q',
    appId: '1:578747395600:web:0614e6337857ec0f136495',
    messagingSenderId: '578747395600',
    projectId: 'coro-app-jovenes-lldm',
    authDomain: 'coro-app-jovenes-lldm.firebaseapp.com',
    storageBucket: 'coro-app-jovenes-lldm.firebasestorage.app',
  );
}
